# Generated by Django 3.2 on 2024-06-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_homegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegallery',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='index'),
        ),
    ]
